<?php
/**
 * @var \Inchoo\StoreReview\Block\Customer\Index $block
 */
$results = $block->getReviews();

?>
<div class="actions-toolbar">
    <div class="primary">
        <a href="<?= $block->getCreatePage(); ?>" class="action save primary"
           title="create">
            <span>Create</span>
        </a>
    </div>
</div>
<br>
<div class="table-wrapper orders-history">
    <table class="table">
        <thead>
        <tr>
            <td>Title</td>
            <td>Created at</td>
            <td>Updated at</td>
            <td>Approved</td>
            <td>Store</td>
            <td>Action</td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($results as $review): ?>
            <tr>
                <td><?= $block->escapeHtml($review->getTitle()); ?></td>
                <td><?= $block->escapeHtml($review->getCreatedAt()); ?></td>
                <td><?= $block->escapeHtml($review->getUpdatedAt()); ?></td>
                <td><?= $block->escapeHtml($block->getApprovedString($review->getApproved())); ?></td>
                <td><?= $block->escapeHtml($block->getStoreWithId($review->getStore())); ?></td>
                <td>
                    <a href="<?= $block->escapeHtml($block->getDeleteUrl($review->getId())); ?>">Delete</a>
                    <a href="<?= $block->escapeHtml($block->getEditUrl($review->getId())); ?>">Edit</a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>