<?php

/**
 * @var \Inchoo\StoreReview\Block\Index $block
 */
?>

    <div class="actions-toolbar">
        <div class="primary">
            <a href="" class="action save primary"
               title="create">
                <span>Create</span>
            </a>
        </div>
    </div>

<div class="table-wrapper orders-history">
    <table class="table">
        <thead>
        <tr>
            <td>Subject</td>
            <td>Closed</td>
            <td>Created at</td>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <a href=""></a>
                </td>
                <td>
                    <input type="checkbox">
                </td>
                <td></td>
            </tr>
        </tbody>
    </table>
</div>

